config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from gtas.parent.views.views import DashboardView

urlpatterns = [
    path("", DashboardView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("gtas.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("parent/", include("gtas.parent.urls", namespace="parent")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

gtas/parent/urls.py
from django.urls import path
from rest_framework import routers

from gtas.parent.views.parent import AirportCRUDView
from gtas.parent.views.parent import AirportRestoreCRUDView
from gtas.parent.views.parent import ApiAccessCRUDView
from gtas.parent.views.parent import AppConfigurationCRUDView
from gtas.parent.views.parent import AuditLogCRUDView
from gtas.parent.views.parent import CarrierCRUDView
from gtas.parent.views.parent import CarrierRestoreCRUDView
from gtas.parent.views.parent import CodeShareFlightCRUDView
from gtas.parent.views.parent import CountryCRUDView
from gtas.parent.views.parent import CountryRestoreCRUDView
from gtas.parent.views.parent import DwellTimeCRUDView
from gtas.parent.views.parent import ErrorDetailCRUDView
from gtas.parent.views.parent import FlightDirectionCRUDView
from gtas.parent.views.parent import NoteTypeCRUDView

from gtas.parent.views.views import DashboardView

app_name = 'parent'

router = routers.DefaultRouter()

urlpatterns = [
    path('airport', AirportCRUDView.as_view(), name='airport_crud'),
    path('airport_restore', AirportRestoreCRUDView.as_view(), name='airport_restore_crud'),
    path('api_access', ApiAccessCRUDView.as_view(), name='api_access_crud'),
    path('app_configuration', AppConfigurationCRUDView.as_view(), name='app_configuration_crud'),
    path('audit_log', AuditLogCRUDView.as_view(), name='audit_log_crud'),
    path('carrier', CarrierCRUDView.as_view(), name='carrier_crud'),
    path('carrier_restore', CarrierRestoreCRUDView.as_view(), name='carrier_restore_crud'),
    path('code_share_flight', CodeShareFlightCRUDView.as_view(), name='code_share_flight_crud'),
    path('country', CountryCRUDView.as_view(), name='country_crud'),
    path('country_restore', CountryRestoreCRUDView.as_view(), name='country_restore_crud'),
    path('dwell_time', DwellTimeCRUDView.as_view(), name='dwell_time_crud'),
    path('error_detail', ErrorDetailCRUDView.as_view(), name='error_detail_crud'),
    path('flight_direction', FlightDirectionCRUDView.as_view(), name='flight_direction_crud'),
    path('note_type', NoteTypeCRUDView.as_view(), name='note_type_crud'),

    path('', DashboardView.as_view(), name='dashboard')
]

gtas/users/urls.py
from django.urls import path

from gtas.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

gtas/parsers/models.py
from django.db import models

# Create your models here.

gtas/parent/api/views.py
from rest_framework import permissions
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework.viewsets import ModelViewSet

from gtas.parent.models.parent import Airport
from gtas.parent.models.parent import AirportRestore
from gtas.parent.models.parent import ApiAccess
from gtas.parent.models.parent import AppConfiguration
from gtas.parent.models.parent import AuditLog
from gtas.parent.models.parent import Carrier
from gtas.parent.models.parent import CarrierRestore
from gtas.parent.models.parent import CodeShareFlight
from gtas.parent.models.parent import Country
from gtas.parent.models.parent import CountryRestore
from gtas.parent.models.parent import DwellTime
from gtas.parent.models.parent import ErrorDetail
from gtas.parent.models.parent import FlightDirection
from gtas.parent.models.parent import NoteType

from gtas.parent.api.serializers import AirportSerializer
from gtas.parent.api.serializers import AirportRestoreSerializer
from gtas.parent.api.serializers import ApiAccessSerializer
from gtas.parent.api.serializers import AppConfigurationSerializer
from gtas.parent.api.serializers import AuditLogSerializer
from gtas.parent.api.serializers import CarrierSerializer
from gtas.parent.api.serializers import CarrierRestoreSerializer
from gtas.parent.api.serializers import CodeShareFlightSerializer
from gtas.parent.api.serializers import CountrySerializer
from gtas.parent.api.serializers import CountryRestoreSerializer
from gtas.parent.api.serializers import DwellTimeSerializer
from gtas.parent.api.serializers import ErrorDetailSerializer
from gtas.parent.api.serializers import FlightDirectionSerializer
from gtas.parent.api.serializers import NoteTypeSerializer


class AirportViewSet(ModelViewSet):
    serializer_class = AirportSerializer
    queryset = Airport.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class AirportRestoreViewSet(ModelViewSet):
    serializer_class = AirportRestoreSerializer
    queryset = AirportRestore.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class ApiAccessViewSet(ModelViewSet):
    serializer_class = ApiAccessSerializer
    queryset = ApiAccess.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class AppConfigurationViewSet(ModelViewSet):
    serializer_class = AppConfigurationSerializer
    queryset = AppConfiguration.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class AuditLogViewSet(ModelViewSet):
    serializer_class = AuditLogSerializer
    queryset = AuditLog.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class CarrierViewSet(ModelViewSet):
    serializer_class = CarrierSerializer
    queryset = Carrier.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class CarrierRestoreViewSet(ModelViewSet):
    serializer_class = CarrierRestoreSerializer
    queryset = CarrierRestore.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class CodeShareFlightViewSet(ModelViewSet):
    serializer_class = CodeShareFlightSerializer
    queryset = CodeShareFlight.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class CountryViewSet(ModelViewSet):
    serializer_class = CountrySerializer
    queryset = Country.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class CountryRestoreViewSet(ModelViewSet):
    serializer_class = CountryRestoreSerializer
    queryset = CountryRestore.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class DwellTimeViewSet(ModelViewSet):
    serializer_class = DwellTimeSerializer
    queryset = DwellTime.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class ErrorDetailViewSet(ModelViewSet):
    serializer_class = ErrorDetailSerializer
    queryset = ErrorDetail.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class FlightDirectionViewSet(ModelViewSet):
    serializer_class = FlightDirectionSerializer
    queryset = FlightDirection.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)


class NoteTypeViewSet(ModelViewSet):
    serializer_class = NoteTypeSerializer
    queryset = NoteType.objects.all()
    authentication_classes = [TokenAuthentication, SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user, updated_by=self.request.user)

    def perform_update(self, serializer):
        serializer.save(updated_by=self.request.user)

gtas/parent/views/parent.py
from django.shortcuts import render
from django.views import View

from gtas.parent.forms.parent import AirportForm
from gtas.parent.forms.parent import AirportRestoreForm
from gtas.parent.forms.parent import ApiAccessForm
from gtas.parent.forms.parent import AppConfigurationForm
from gtas.parent.forms.parent import AuditLogForm
from gtas.parent.forms.parent import CarrierForm
from gtas.parent.forms.parent import CarrierRestoreForm
from gtas.parent.forms.parent import CodeShareFlightForm
from gtas.parent.forms.parent import CountryForm
from gtas.parent.forms.parent import CountryRestoreForm
from gtas.parent.forms.parent import DwellTimeForm
from gtas.parent.forms.parent import ErrorDetailForm
from gtas.parent.forms.parent import FlightDirectionForm
from gtas.parent.forms.parent import NoteTypeForm


class AirportCRUDView(View):
    template_view = "parent/airport.html"

    def get(self, request):
        form = AirportForm()
        return render(request, "parent/airport.html", {"form": form})


class AirportRestoreCRUDView(View):
    template_view = "parent/airport_restore.html"

    def get(self, request):
        form = AirportRestoreForm()
        return render(request, "parent/airport_restore.html", {"form": form})


class ApiAccessCRUDView(View):
    template_view = "parent/api_access.html"

    def get(self, request):
        form = ApiAccessForm()
        return render(request, "parent/api_access.html", {"form": form})


class AppConfigurationCRUDView(View):
    template_view = "parent/app_configuration.html"

    def get(self, request):
        form = AppConfigurationForm()
        return render(request, "parent/app_configuration.html", {"form": form})


class AuditLogCRUDView(View):
    template_view = "parent/audit_log.html"

    def get(self, request):
        form = AuditLogForm()
        return render(request, "parent/audit_log.html", {"form": form})


class CarrierCRUDView(View):
    template_view = "parent/carrier.html"

    def get(self, request):
        form = CarrierForm()
        return render(request, "parent/carrier.html", {"form": form})


class CarrierRestoreCRUDView(View):
    template_view = "parent/carrier_restore.html"

    def get(self, request):
        form = CarrierRestoreForm()
        return render(request, "parent/carrier_restore.html", {"form": form})


class CodeShareFlightCRUDView(View):
    template_view = "parent/code_share_flight.html"

    def get(self, request):
        form = CodeShareFlightForm()
        return render(request, "parent/code_share_flight.html", {"form": form})


class CountryCRUDView(View):
    template_view = "parent/country.html"

    def get(self, request):
        form = CountryForm()
        return render(request, "parent/country.html", {"form": form})


class CountryRestoreCRUDView(View):
    template_view = "parent/country_restore.html"

    def get(self, request):
        form = CountryRestoreForm()
        return render(request, "parent/country_restore.html", {"form": form})


class DwellTimeCRUDView(View):
    template_view = "parent/dwell_time.html"

    def get(self, request):
        form = DwellTimeForm()
        return render(request, "parent/dwell_time.html", {"form": form})


class ErrorDetailCRUDView(View):
    template_view = "parent/error_detail.html"

    def get(self, request):
        form = ErrorDetailForm()
        return render(request, "parent/error_detail.html", {"form": form})


class FlightDirectionCRUDView(View):
    template_view = "parent/flight_direction.html"

    def get(self, request):
        form = FlightDirectionForm()
        return render(request, "parent/flight_direction.html", {"form": form})


class NoteTypeCRUDView(View):
    template_view = "parent/note_type.html"

    def get(self, request):
        form = NoteTypeForm()
        return render(request, "parent/note_type.html", {"form": form})

gtas/parent/views/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin


class DashboardView(LoginRequiredMixin, View):
    template_name = "parent/dashboard.html"

    def get(self, request):
        return render(request, 'parent/dashboard.html')

gtas/parsers/views.py
from django.shortcuts import render

# Create your views here.

gtas/templates/base-with-menu.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<meta content="text/html;charset=UTF-8" http-equiv="content-type"/>
<head>
	<title>{% block title %}{% endblock title %}</title>

	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" name="viewport">
	<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
	<meta content="Global Travel Assessment System" name="description"/>
	<meta content="gtas" name="keywords"/>
	<meta content="minelytics" name="author"/>

	<link href="{% static 'assets/images/favicon.ico' %}" rel="icon" type="image/x-icon">

	<link href="{% static 'bower_components/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/pages/waves/css/waves.min.css' %}" media="all" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/icon/feather/css/feather.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/icon/themify-icons/themify-icons.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/icon/icofont/css/icofont.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/icon/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/pages/prism/prism.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/pcoded-horizontal.min.html' %}" rel="stylesheet" type="text/html">

	{% block stylesheets %}{% endblock stylesheets %}
</head>

<body>

<div class="loader-bg">
	<div class="loader-bar"></div>
</div>

<div class="pcoded" id="pcoded">
	<div class="pcoded-overlay-box"></div>
	<div class="pcoded-container navbar-wrapper">

		{% include "navbar.html" %}

		<div class="pcoded-main-container">
			<div class="pcoded-wrapper">
				{% include "menu.html" %}
				{% block body %}{% endblock body %}
			</div>
		</div>

	</div>
</div>

	<script src="{% static 'bower_components/jquery/js/jquery.min.js' %}"></script>
	<script src="{% static 'bower_components/jquery-ui/js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'bower_components/popper.js/js/popper.min.js' %}"></script>
	<script src="{% static 'bower_components/bootstrap/js/bootstrap.min.js' %}"></script>

	<script src="{% static 'assets/pages/waves/js/waves.min.js' %}"></script>

	<script src="{% static 'bower_components/jquery-slimscroll/js/jquery.slimscroll.js' %}"></script>

	<script src="{% static 'bower_components/modernizr/js/modernizr.js' %}"></script>
	<script src="{% static 'bower_components/modernizr/js/css-scrollbars.js' %}"></script>

	<script src="{% static 'assets/pages/prism/custom-prism.js' %}"></script>

	<script src="{% static 'bower_components/i18next/js/i18next.min.js' %}"></script>
	<script src="{% static 'bower_components/i18next-xhr-backend/js/i18nextXHRBackend.min.js' %}"></script>
	<script src="{% static 'bower_components/i18next-browser-languagedetector/js/i18nextBrowserLanguageDetector.min.js' %}"></script>
	<script src="{% static 'bower_components/jquery-i18next/js/jquery-i18next.min.js' %}"></script>

	<script src="{% static 'assets/js/pcoded.min.js' %}"></script>
	<script src="{% static 'assets/js/vertical/menu/menu-hori-fixed.js' %}"></script>
	<script src="{% static 'assets/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
	<script src="{% static 'assets/js/script.js' %}"></script>

	{% block javascripts %}{% endblock javascripts %}
</body>

</html>

gtas/templates/base-without-menu.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<meta content="text/html;charset=UTF-8" http-equiv="content-type"/>
<head>
	<title>{% block title %}{% endblock title %}</title>

	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" name="viewport">
	<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
	<meta content="Global Travel Assessment System" name="description"/>
	<meta content="gtas" name="keywords"/>
	<meta content="minelytics" name="author"/>

	<link href="{% static 'assets/images/favicon.ico' %}" rel="icon" type="image/x-icon">
	<link href="{% static 'bower_components/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"
	      type="text/css">

	<link href="{% static 'assets/pages/waves/css/waves.min.css' %}" media="all" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/icon/feather/css/feather.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/icon/themify-icons/themify-icons.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/icon/icofont/css/icofont.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/icon/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

	<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'assets/css/pages.css' %}" rel="stylesheet" type="text/css">

	{% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
	{% block body %}{% endblock body %}

	<script src="{% static 'bower_components/jquery/js/jquery.min.js' %}"></script>
	<script src="{% static 'bower_components/jquery-ui/js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'bower_components/popper.js/js/popper.min.js' %}"></script>
	<script src="{% static 'bower_components/bootstrap/js/bootstrap.min.js' %}"></script>

	<script src="{% static 'assets/pages/waves/js/waves.min.js' %}"></script>
	<script src="{% static 'bower_components/jquery-slimscroll/js/jquery.slimscroll.js' %}"></script>

	<script src="{% static 'bower_components/modernizr/js/modernizr.js' %}"></script>
	<script src="{% static 'bower_components/modernizr/js/css-scrollbars.js' %}"></script>
	<script src="{% static 'assets/js/common-pages.js' %}"></script>

	{% block javascripts %}{% endblock javascripts %}
</body>

</html>

gtas/templates/menu.html
<nav class="pcoded-navbar">
	<div class="pcoded-inner-navbar">
		<ul class="pcoded-item">
			<li class="pcoded-hasmenu">
				<a class="waves-effect waves-dark" href="javascript:void(0)">
					<span class="pcoded-micon"><i class="feather icon-grid"></i></span>
					<span class="pcoded-mtext">Tools</span>
				</a>
				<ul class="pcoded-submenu">
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext">Queries</span>
						</a>
					</li>
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext" data-i18n="nav.navigate.main">Rules</span>
						</a>
					</li>
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext" data-i18n="nav.navigate.main">Watch List</span>
						</a>
					</li>
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext" data-i18n="nav.navigate.main">Admin</span>
						</a>
					</li>
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext" data-i18n="nav.navigate.main">Neo4J Browser</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="">
				<a class="waves-effect waves-dark" href="">
					<span class="pcoded-micon"><i class="feather icon-navigation"></i></span>
					<span class="pcoded-mtext" data-i18n="nav.navigate.main">Flights</span>
				</a>
			</li>
			<li class="">
				<a class="waves-effect waves-dark" href="">
					<span class="pcoded-micon"><i class="feather icon-folder"></i></span>
					<span class="pcoded-mtext" data-i18n="nav.navigate.main">Priority Vetting List</span>
				</a>
			</li>
			<li class="pcoded-hasmenu">
				<a class="waves-effect waves-dark" href="javascript:void(0)">
					<span class="pcoded-micon"><i class="feather icon-help-circle"></i></span>
					<span class="pcoded-mtext">Help</span>
				</a>
				<ul class="pcoded-submenu">
					<li class="">
						<a class="waves-effect waves-dark" href="">
							<span class="pcoded-mtext" data-i18n="nav.navigate.main">About</span>
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
</nav>

gtas/templates/navbar.html
{% load static %}
<nav class="navbar header-navbar pcoded-header">
	<div class="navbar-wrapper">
		<div class="navbar-logo">
			<a href="index.html">
				<img alt="Theme-Logo" class="img-fluid" src="{% static 'assets/images/logo.png' %}"/>
			</a>
			<a class="mobile-menu" href="#!" id="mobile-collapse">
				<i class="feather icon-menu icon-toggle-right"></i>
			</a>
			<a class="mobile-options waves-effect waves-light">
				<i class="feather icon-more-horizontal"></i>
			</a>
		</div>
		<div class="navbar-container container-fluid">
			<ul class="nav-left">
				<li class="header-search">
					<div class="main-search morphsearch-search">
						<div class="input-group">
							<span class="input-group-prepend search-close">
								<i class="feather icon-x input-group-text"></i>
							</span>
							<input class="form-control" placeholder="Enter Keyword" type="text">
							<span class="input-group-append search-btn">
								<i class="feather icon-search input-group-text"></i>
							</span>
						</div>
					</div>
				</li>
			</ul>
			<ul class="nav-right">
				<li class="user-profile header-notification">
					<div class="dropdown-primary dropdown">
						<div class="dropdown-toggle" data-toggle="dropdown">
							<span>{{ user.get_username }}</span>
							<i class="feather icon-chevron-down"></i>
						</div>
						<ul class="show-notification profile-notification dropdown-menu"
						    data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
							<li>
								<a href="{% url 'users:detail' user.get_username %}">
									<i class="feather icon-user"></i> Profile
								</a>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">
									<i class="feather icon-log-out"></i> Logout
								</a>
							</li>
						</ul>
					</div>
				</li>
			</ul>
		</div>
	</div>
</nav>